version: '{build}'

image: Ubuntu

environment:
  # Disable Powershell on Linux machines
  APPVEYOR_YML_DISABLE_PS_LINUX: "true"

configuration: Release

artifacts:
  - path: 'charts/*.tgz'

install:
  - sh: sudo apt-get -y update;
  - sh: sudo apt-get install  -y conntrack;
  - sh: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

test_script:
  - sh: cd xcube-gen
  - sh: helm dependencies update
  - sh: helm lint . -f tests/test-values.yaml
  - sh: helm package -d ../charts .
  - sh: cd ..
  - sh: cd xcube-geodb
  - sh: helm dependencies update
  - sh: helm lint . -f tests/test-values.yaml
  - sh: helm package -d ../charts .
  - sh: cd ..
  - sh: ls -al charts


deploy:
  - provider: Environment
    name: dcfs-xcube-charts

