kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "xcube-gen.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "xcube-gen.serviceAccountName" . }}
    namespace: {{ .Values.webapiContainer.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io