kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xcube-gen
subjects:
  - kind: ServiceAccount
    name: {{ include "xcube-gen.serviceAccountName" . }}
    namespace: xcube-gen
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io