apiVersion: v1
kind: ConfigMap
metadata:
  name: xcube-datapools
data:
  data-pools.yaml: |-
{{ .Files.Get "cfgs/data-pools.yaml" | indent 4 }}
  stores-schema.json: |-
{{ .Files.Get "cfgs/stores-schema.json" | indent 4 }}