apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcube-gen.fullname" . }}
  labels:
    {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xcube-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xcube-gen.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xcube-gen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if .Values.image.dev }}
          image: "{{ .Values.image.dev_img }}"
          {{ else }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          {{ end }}
          env:
            - name: SH_CLIENT_ID
              value: {{.Values.image.env.sh_client_id}}
            - name: SH_CLIENT_SECRET
              value: {{.Values.image.env.sh_client_secret}}
            - name: SH_INSTANCE_ID
              value: {{.Values.image.env.sh_instance_id}}
            - name: XCUBE_SH_DOCKER_IMG
              value: {{.Values.image.env.xcube_sh_docker_img}}
            - name: K8S_NAMESPACE
              value: {{.Values.image.env.k8s_namespace}}
            - name: K8S_PROCESSS_NAMESPACE
              value: {{.Values.image.env.k8s_namespace}}-process
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.container.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
