apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{.Values.docsContainer.name}}
  labels:
    {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.docsContainer.replicaCount }}
  selector:
    matchLabels:
      {{- include "xcube-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xcube-gen.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xcube-gen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.docsContainer.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if .Values.docsContainer.dev }}
          image: "{{ .Values.docsContainer.dev_img }}"
          {{ else }}
          image: "{{ .Values.docsContainer.repository }}:{{ .Chart.AppVersion }}"
          {{ end }}
          imagePullPolicy: {{ .Values.docsContainer.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.docsContainer.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.docsContainer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
