{{ if .Values.keycloakContainer.spawn }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{.Values.keycloakContainer.name}}
  labels:
    {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.keycloakContainer.replicaCount }}
  selector:
    matchLabels:
      {{- include "xcube-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{ if .Values.webapiContainer.rollme }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
      labels:
        {{- include "xcube-gen.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xcube-gen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- toYaml .Values.keycloakContainer.volumes | nindent 8 }}
      containers:
        - name: {{ .Values.webapiContainer.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.keycloakContainer.repository }}:{{ .Values.keycloakContainer.tag }}"
          env:
            - name: XCUBE_GEN_CHART_VERSION
              value: {{.Chart.Version}}
        {{- range .Values.keycloakContainer.env }}
            - name: {{ .name }}
              value: '{{ .value }}'
        {{- end }}
          imagePullPolicy: {{ .Values.webapiContainer.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.keycloakContainer.port}}
              protocol: TCP
            - name: debug
              containerPort: 8003
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            {{- toYaml .Values.keycloakContainer.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.keycloakContainer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{ .Values.keycloakContainer.name }}
  labels:
  {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.keycloakContainer.port }}
      targetPort: {{ .Values.keycloakContainer.port }}
      protocol: TCP
      name: http
  selector:
  {{- include "xcube-gen.selectorLabels" . | nindent 4 }}

{{ end }}