{{ if .Values.redisContainer.spawn }}

apiVersion: v1
data:
  redis-config: |
    {{- range .Values.redisContainer.config }}
    {{ .name }} {{ .value }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{.Values.redisContainer.name}}-cfg

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{.Values.redisContainer.name}}
  labels:
  {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redisContainer.replicaCount }}
  selector:
    matchLabels:
  {{- include "xcube-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "xcube-gen.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xcube-gen.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.redisContainer.name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redisContainer.repository }}"
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: XCUBE_GEN_CHART_VERSION
              value: {{.Chart.Version}}
            {{- range .Values.redisContainer.env }}
            - name: {{ .name }}
              value: '{{ .value }}'
            {{- end }}
            - name: MASTER
              value: "true"
          imagePullPolicy: {{ .Values.redisContainer.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.redisContainer.port}}
              protocol: TCP
          volumeMounts:
          - mountPath: /redis-master-data
            name: data
          - mountPath: /redis-master
            name: config
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
          resources:
            {{- toYaml .Values.redisContainer.resources | nindent 12 }}
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: xcube-gen-redis-config
            items:
              - key: redis-config
                path: redis.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{ .Values.redisContainer.name }}
  labels:
  {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.redisContainer.port }}
      targetPort: {{ .Values.redisContainer.port }}
      protocol: TCP
      name: http
  selector:
  {{- include "xcube-gen.selectorLabels" . | nindent 4 }}

 {{ end }}