{{ if .Values.uiContainer.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{.Values.uiContainer.name}}
  labels:
    {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.uiContainer.replicaCount }}
  selector:
    matchLabels:
      {{- include "xcube-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{ if .Values.uiContainer.rollme }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
      labels:
        {{- include "xcube-gen.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xcube-gen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "xcube-gen.fullname" . }}-{{.Values.uiContainer.name}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.uiContainer.repository }}:{{ .Values.uiContainer.tag }}"
          env:
            {{- range .Values.uiContainer.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          imagePullPolicy: {{ .Values.uiContainer.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.uiContainer.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.uiContainer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{ .Values.uiContainer.name }}
  labels:
  {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.uiContainer.port }}
      targetPort: {{ .Values.uiContainer.port }}
      protocol: TCP
      name: http
  selector:
  {{- include "xcube-gen.selectorLabels" . | nindent 4 }}

{{ end }}