apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{.Values.webapiContainer.name}}
  labels:
    {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webapiContainer.replicaCount }}
  selector:
    matchLabels:
      {{- include "xcube-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{ if .Values.webapiContainer.rollme }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
      labels:
        {{- include "xcube-gen.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xcube-gen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webapiContainer.securityContext | nindent 8 }}
      volumes:
        {{- toYaml .Values.webapiContainer.volumes | nindent 8 }}
      initContainers:
        - name: pull-xcubegen
          image: {{ .Values.webapiContainer.xcubeGenImage }}
          command:
            - /bin/bash
            - -c
            - ls
      containers:
        - name: {{ .Values.webapiContainer.name }}
          command:
            {{ range .Values.webapiContainer.command }}
            - "{{ . }}"
            {{ end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.webapiContainer.repository}}:{{.Values.webapiContainer.tag}}
          env:
            - name: XCUBE_GEN_CHART_VERSION
              value: {{.Chart.Version}}
        {{- range .Values.webapiContainer.env }}
            - name: {{ .name }}
              value: '{{ .value }}'
        {{- end }}
          imagePullPolicy: {{ .Values.webapiContainer.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.webapiContainer.port}}
              protocol: TCP
            - name: debug
              containerPort: 8003
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v2
              port: http
          readinessProbe:
            httpGet:
              path: /api/v2
              port: http
          volumeMounts:
            {{- toYaml .Values.webapiContainer.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.webapiContainer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcube-gen.fullname" . }}-{{ .Values.webapiContainer.name }}
  labels:
  {{- include "xcube-gen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.webapiContainer.port }}
      targetPort: {{ .Values.webapiContainer.port }}
      protocol: TCP
      name: http
  selector:
  {{- include "xcube-gen.selectorLabels" . | nindent 4 }}
