apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dcfs-xcube-gen-production
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 3
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
