apiVersion: apps/v1
kind: Deployment
metadata:
  name: "xcube-gen"
  namespace: "xcube-gen"
spec:
  selector:
    matchLabels:
      app: "xcube-gen"
  replicas: 1
  template:
    metadata:
      labels:
        app: "xcube-gen"
    spec:
      containers:
        - image: quay.io/bcdev/xcube-gen@sha256:954e992a76cb3b837e87094f770561527223d1374f4333a2f2a06806e5509095
          env:
            - name: XCUBE_SH_DOCKER_IMG
              value: "quay.io/bcdev/xcube-sh@sha256:225d0dc76578e965c8ab267f5fdf22b8423b1bbc4cbd3a288df2fd30223fbcf8"
          imagePullPolicy: Always
          name: "xcube-gen"
          ports:
            - containerPort: 8000
        - image: quay.io/bcdev/xcube-gen-ui:0.4.0.dev0
          imagePullPolicy: Always
          name: "xcube-gen-ui"
          ports:
            - containerPort: 80


