apiVersion: apps/v1
kind: Deployment
metadata:
  name: "xcube-gen"
  namespace: "xcube-gen"
spec:
  selector:
    matchLabels:
      app: "xcube-gen"
  replicas: 1
  template:
    metadata:
      labels:
        app: "xcube-gen"
    spec:
      containers:
        - image: quay.io/bcdev/xcube-gen@sha256:954e992a76cb3b837e87094f770561527223d1374f4333a2f2a06806e5509095
          env:
            - name: SH_CLIENT_ID
              value: c523d6d6-e43a-4b2c-9b3c-5fd179223d50
            - name: SH_CLIENT_SECRET
              value: j5jDeDhSWCBEyikj6ooq
            - name: SH_INSTANCE_ID
              value: c5828fc7-aa47-4f1d-b684-ae596521ef25
            - name: AWS_ACCESS_KEY_ID
              value: AKIAJ4WLU2C67PM2TBOQ
            - name: AWS_ACCESS_KEY_SECRET
              value: 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
            - name: XCUBE_SH_DOCKER_IMG
              value: "quay.io/bcdev/xcube-sh@sha256:225d0dc76578e965c8ab267f5fdf22b8423b1bbc4cbd3a288df2fd30223fbcf8"
          imagePullPolicy: Always
          name: "xcube-gen"
          ports:
            - containerPort: 8000
        - image: quay.io/bcdev/xcube-gen-ui:0.4.0.dev0
          imagePullPolicy: Always
          name: "xcube-gen-ui"
          ports:
            - containerPort: 80


