{{ $values := .Values }}
{{ $chart := .Chart }}
{{ $root := . }}

{{ range $i, $deployment := .Values.databases}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "xcube-geodb.fullname" $root }}-{{$deployment.name}}
  labels:
    {{- include "xcube-geodb.labels" $root | nindent 4 }}
spec:
  replicas: {{ $deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "xcube-geodb.selectorLabels" $root | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xcube-geodb.selectorLabels" $root | nindent 8 }}
    spec:
    {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xcube-geodb.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $deployment.name }}
          securityContext:
            {{- toYaml $values.securityContext | nindent 12 }}
          image: "{{ $deployment.repository }}"
          env:
            - name: XCUBE_GEN_CHART_VERSION
              value: {{ $chart.Version }}
        {{ range $deployment.env }}
            - name: {{ .name }}
              value: '{{ .value }}'
        {{ end }}
          imagePullPolicy: {{ $deployment.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $deployment.port }}
              protocol: TCP
        {{ if $deployment.probes }}
          readinessProbe:
            exec:
              command: ["psql", "-U", "postgres", "-d", "geodb", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-U", "postgres", "-d", "geodb", "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
        {{ end }}
          resources:
            {{- toYaml $deployment.resources | nindent 12 }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
{{ end }}