{{ $values := .Values }}
{{ $chart := .Chart }}
{{ $root := . }}

{{ range $i, $deployment := .Values.webservices}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "xcube-geodb.fullname" $root }}-{{$deployment.name}}
  labels:
    {{- include "xcube-geodb.labels" $root | nindent 4 }}
spec:
  replicas: {{ $deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ $deployment.name }}
  template:
    metadata:
      labels:
        project: dcfs
        app: {{ $deployment.name }}
    spec:
    {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xcube-geodb.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        - name: bcdev-tu-bcdev-pull-secret
      containers:
        - name: {{ $deployment.name }}
          securityContext:
            {{- toYaml $values.securityContext | nindent 12 }}
          image: "{{ $deployment.repository }}"
          env:
            - name: XCUBE_GEN_CHART_VERSION
              value: {{ $chart.Version }}
        {{- range $deployment.env }}
            - name: {{ .name }}
              value: '{{ .value }}'
        {{- end }}
          imagePullPolicy: {{ $deployment.pullPolicy }}
          ports:
            - name: svc-{{ $deployment.name }}
              containerPort: {{ $deployment.port }}
              protocol: TCP
          {{ if $deployment.probes }}
          livenessProbe:
            httpGet:
              path: /
              port: svc-{{ $deployment.name }}
              httpHeaders:
                - name: access
                  value: liveness
          readinessProbe:
            httpGet:
              path: /
              port: svc-{{ $deployment.name }}
              httpHeaders:
                - name: access
                  value: liveness
          {{ end }}
          resources:
            {{- toYaml $deployment.resources | nindent 12 }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
{{ end }}