{{ $values := .Values }}
{{ $chart := .Chart }}
{{ $root := . }}

{{ range $i, $deployment := .Values.webservices }}
apiVersion: v1
kind: Service
metadata:
  name: svc-{{ $deployment.name }}
  labels:
    {{- include "xcube-geodb.labels" $root | nindent 4 }}
spec:
  type: {{ $values.service.type }}
  ports:
    - port: {{ $deployment.servicePort }}
      targetPort: {{ $deployment.port }}
      protocol: TCP
      name: svc-{{ $deployment.name }}
  selector:
    app: {{ $deployment.name }}

---
{{ end }}

