apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcube-geodb.fullname" . }}-{{.Values.webapiContainer.name}}
  labels:
    {{- include "xcube-geodb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webapiContainer.replicaCount }}
  selector:
    matchLabels:
      {{- include "xcube-geodb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{ if .Values.webapiContainer.rollme }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
      labels:
        {{- include "xcube-geodb.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xcube-geodb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webapiContainer.securityContext | nindent 8 }}
      volumes:
        {{- toYaml .Values.webapiContainer.volumes | nindent 8 }}
      containers:
        - name: {{ .Values.webapiContainer.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.webapiContainer.repository }}:{{ .Values.webapiContainer.tag }}
          {{ if .Values.webapiContainer.overrideCommand }}
          command: {{ .Values.webapiContainer.command }}
          args: {{ .Values.webapiContainer.args }}
          {{ end }}
          env:
            - name: XCUBE_GEN_CHART_VERSION
              value: {{.Chart.Version}}
        {{- range .Values.webapiContainer.env }}
            - name: {{ .name }}
              value: '{{ .value }}'
        {{- end }}
          imagePullPolicy: {{ .Values.webapiContainer.pullPolicy }}
          ports:
            - name: svc-{{ .Values.webapiContainer.name }}
              containerPort: {{.Values.webapiContainer.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: svc-{{ .Values.webapiContainer.name }}
          readinessProbe:
            httpGet:
              path: /
              port: svc-{{ .Values.webapiContainer.name }}
          volumeMounts:
            {{- toYaml .Values.webapiContainer.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.webapiContainer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.webapiContainer.name }}
  labels:
  {{- include "xcube-geodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.webapiContainer.port }}
      targetPort: {{ .Values.webapiContainer.port }}
      protocol: TCP
      name: svc-{{ .Values.webapiContainer.name }}
  selector:
  {{- include "xcube-geodb.selectorLabels" . | nindent 4 }}
